version: "3.8"
services:
  pentaho-pg:
    image: postgres
    volumes:
      - "~/data:/var/lib/postgresql/data/"
    ports: 
      - "5432:5432"
    environment:
      - 'POSTGRES_USER=pgadmin'
      - 'POSTGRES_PASSWORD=pgadmin'
    restart: always
  pentaho:
    image: pentaho-server-ce
    ports:
      - "8080:8080"
    environment:
      - 'PGHOST=pentaho-pg'
    depends_on:
      - pentaho-pg
    restart: always