version: "3.8"
services:
  pentaho-pg:
    image: postgres
    volumes:
      - "~/data:/var/lib/postgresql/data/"
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=pentaho
      - POSTGRES_PASSWORD=password
    restart: always
  pentaho:
    image: pentaho-server-ce
    ports:
      - "8080:8080"
    environment:
      - PGHOST=pentaho-pg
      - PGUSER=pentaho
      - PGPASSWORD=password 
    depends_on:
      - pentaho-pg
    restart: always